GET https://example.com/comments/1 HTTP/1.1

###

GET https://example.com/topics/1 HTTP/1.1

###

POST http://127.0.0.1:8000/api/users HTTP/1.1
content-type: application/json

{
    "name": "Luiza",
    "email": "luiza@example.com",
    "age": 18,
    "address": "123 Main Street"
}
